name: Deploy Kubonnaci
on:
  push:
    branches:
      - main
      - master

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: |-
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t arjunank/react-test -f ./client/Dockerfile.dev ./client
        docker run -e CI=true arjunank/react-test npm test

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.24.0'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: kubonacciecs
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t multi-client ./client
        docker build -t multi-server ./server
        docker build -t multi-worker ./worker

        docker tag multi-client:latest $ECR_REGISTRY/multi-client:latest
        docker tag multi-server:latest $ECR_REGISTRY/multi-server:latest
        docker tag multi-worker:latest $ECR_REGISTRY/multi-worker:latest

        docker push $ECR_REGISTRY/multi-client:latest
        docker push $ECR_REGISTRY/multi-server:latest
        docker push $ECR_REGISTRY/multi-worker:latest